name: build

on: 
  push:

jobs:
  release-versions:
    name: Build narray-fromfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version : 2.7
      - name: Install dependencies
        run: bundle install
      - name: Compile C
        run: rake compile:fromfile
      - name: build gem
        run: gem build narray-fromfile.gemspec
      - name: install gem
        run: gem install narray-fromfile-*.gem
      - name: Test
        run: rake test
      