name: build

on: 
  push:

jobs:
  release-versions:
    name: Build narray-fromfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version : 2.7
      - name: Install a specific_install gem
        run: gem install specific_install --no-document
      - name: Install fromfile gems.
        run: gem specific_install -l "git://github.com/himeyama/narray-fromfile.git"
      - name: test1
        run: ./test.rb
      - name: test2
        run: od -t fD data.bin
      - name: uninstall gems
        run: gem uninstall narray-fromfile numo-narray
        
      